language: node_js
sudo: false
node_js:
- stable
cache:
  directories:
  - node_modules
env:
  global:
  - secure: LjqDk07qRtDzue/VzlWiRsLss/XSwNcJ9qCXaCwVWFc2UDJfWAVugJuzM2qrtHaxEdIgSgYUfFqgtJnVslBvJ/3nieaoLe4qPjy6h2lH2GE+l7UsdC1IGHWoPj6pkdu5Xgkl+Yv42epdXxThn7L/kFKlZISI7WUJm+6hMpB6KzI=
  - secure: FoDXxc0heIq1WxiReupWbxD5XE3FZj1RK2NZ5W4obiCJN6nGthXOBBzFSflHBqEHFI3to7mtaFC7/8y5Kl++y223RmrRyR/UaA2eXFMWWgGghv6oiZNkayuit14F3TRGjaRulQzp3badH6cDY2F8G79rYeSE6ZOI5g6UeV/bi20=
  matrix:
  - BROWSER=PhantomJS
  - BROWSER=SL_Chrome
  - BROWSER=SL_Firefox
  - BROWSER=SL_Safari
  - BROWSER=SL_IE_9
  - BROWSER=SL_IE_10
  - BROWSER=SL_IE_11
