language: node_js
sudo: false
node_js:
- stable
cache:
  directories:
  - node_modules
env:
  global:
  - secure: D/67AymLbpBixRkny092e6DiNd+ycAWsSlIkYEFqc5eP0BC4043v0l516ttLu/DBQ02IfmDvvDmIJzN6y1VhNj0UA5nv+ze3A6AwJ8JugxnoTQm35Po6KUAS5+Mdd8FLwxW6cVTXN1rUSOTaUZTE4g5HLZRIYKinyYftP9pXYt4=
  - secure: TCjeSbYKfS3Y7nfUS/Nn7bfTMGy1Ys0Vp37zRYX/Z6GH71QWQ97HGMtPqzI5DWp2iDCInWUFtoD0m8jkpNfbJKPVIJ2bNJxUUx4fkgurSDKnHlto/GvLks76cJgSmMO27kT5S863SxPsrDolnTmKSr4KQr8nTY9a0QhCHxxvQx8=
  matrix:
  - BROWSER=PhantomJS
  - BROWSER=SL_Chrome
  - BROWSER=SL_Firefox
  - BROWSER=SL_Safari
  - BROWSER=SL_IE_8
  - BROWSER=SL_IE_9
  - BROWSER=SL_IE_10
  - BROWSER=SL_IE_11
